### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by rogercreagh** [rogercreagh/j5-xbArticleMan#4]
reported by @BernSgo
Describe the bug
After yesterday update the old error message disappears, but a new one is there

To Reproduce

Expected behavior

Screenshots
[xbArticleMan_Dienstag, 11  Juni 2024_08h16m11s_001_](https://private-user-images.githubusercontent.com/165266578/338461380-4371434c-4d92-4bb2-8939-8a2be5801dbf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDQyNzksIm5iZiI6MTcxODEwMzk3OSwicGF0aCI6Ii8xNjUyNjY1NzgvMzM4NDYxMzgwLTQzNzE0MzRjLTRkOTItNGJiMi04OTM5LThhMmJlNTgwMWRiZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxMTA2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTFlY2NiMGVkZGRlYTFmZGI5Mzc5MjcxMmQ5MmFhZDMyMzZkOGE4NDI2M2RmNTUyYmQ3ZmNjMTFlYjgzZmM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AIReuO-7TDpiVPhFm4reB6u9vH1vXXQi7VPedjTwFB0)

*Server (please provide at least Joomla and php versions)

Joomla Version: [5.1.1]
PHP Version [8.2.16]
MySQL version 8.0.26-16
Server type and OS [Linux Provider version]
Client (please complete the following information):

Type [Windows PC]
Device OS Version Windows 10 newest
Browser [firefox and othersi]

Smartphone

Additional context
It is a great tool, thanks for this - Bernhard

**Comment by rogercreagh** [comment]
@BernSgo I think this must be a conflict with MySQL v8.0.26-16
I have been testing using MariaDb 10.6.16-MariaDB-0ubuntu0.22.04.1 on which I can't reprodce it.
I think MariaDB must be more tolerant of unescaped regex special characters.

In which case there should also be an error on the ArtScodes view.

There is a trial version to test as a pre-release v5.0.0.3-beta1 on here https://github.com/rogercreagh/j5-xbArticleMan/releases/download/v5.0.0.3-beta-1/com_xbarticleman-j5_v5.0.0.3-beta1.zip

Could you let me know if this fixes it for you.

**Comment by BernSgo** [comment]
Hi Roger,

with 5.0.0.3-beta all is fine now. See screenshots - 1 is of system information MySQL 8.
But I tested it too on my own cloud server with **mariadb. Okay too.**
![xbArticleMan-5 0 0 3-beta_Dienstag, 11  Juni 2024_13h23m39s_001_](https://github.com/rogercreagh/j5-xbArticleMan/assets/165266578/39a4069b-27ad-41fc-96f3-91ea822d87a6)
![xbArticleMan-System_Dienstag, 11  Juni 2024_13h25m32s_002_](https://github.com/rogercreagh/j5-xbArticleMan/assets/165266578/352c5305-b503-4133-a182-b5ff711f5a05)


Many thanks for your help - Bernhard

**Comment by rogercreagh** [comment]
Thanks for your help Bernhard

**Comment by rogercreagh** [comment]
Fixed in Release v5.0.0.3 available for download under releases here and for update via joomla update system
